import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Robot;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;

import javax.swing.JButton;
import javax.swing.JPanel;


	public class VentanaUrgencias1 extends javax.swing.JFrame {

	    /**
	     * Creates new form VentanaUrgencias
	     */
		int pantallas;
		
	    public VentanaUrgencias1() {
			//	Determinar número de pantallas

	    	pantallas = InicioIanus.numeroPantallas;
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    private void initComponents() {

	    	setTitle("Urgencias");
	    	setSize(500,140);
	    	setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
	    	
	    	panelN = new JPanel();
	    	panel = new JPanel();
	    	
	    	
	        jButton1 = new javax.swing.JButton();
	        jButton2 = new JButton("Informe urg.");
	        jButton3 = new JButton("Enfermeria urg.");


	        jButton1.setBackground(new java.awt.Color(255, 246, 143));
	        jButton1.setFont(new java.awt.Font("Times", Font.BOLD, 22)); // NOI18N
	        jButton1.setText("Urgencias");
	        jButton1.setToolTipText("Pega en el Ianus la palabra Urg");
	        
	        jButton2.setBackground(new java.awt.Color(152, 245, 255));
	        jButton2.setFont(new java.awt.Font("Times", 1, 22)); // NOI18N
	        jButton2.setToolTipText("Pega en el Ianus la palabra Informe urg.");
	        
	        jButton3.setBackground(new java.awt.Color(193, 255, 193));
	        jButton3.setFont(new java.awt.Font("Times", 1, 22)); // NOI18N
	        jButton3.setToolTipText("Pega en el Ianus la palabra Enfermeria urg.");
	        
	      //  panelN.setLayout(new BorderLayout());
	        panelN.add(jButton2);
	        panelN.add(jButton3);
	        
	        panel.setLayout(new BorderLayout());
	        panel.add(panelN,BorderLayout.SOUTH);
	        panel.add(jButton1,BorderLayout.CENTER);
	        
	        this.setContentPane(panel);
	        
	        //	Clase anónima
	        jButton1.addActionListener (new ActionListener()
	        {
	          public void actionPerformed (ActionEvent e)
	          {
	        	  imprime("URG");
	          }
	        });
	        
	        jButton2.addActionListener (new ActionListener()
	        {
	          public void actionPerformed (ActionEvent e)
	          {
	        	  imprime("Informe urg.");
	          }
	        });
	        
	        jButton3.addActionListener (new ActionListener()
	        {
	          public void actionPerformed (ActionEvent e)
	          {
	        	  imprime("Enfermería urg.");
	          }
	        });
	        
	    }
	    
	        public void imprime(String cadena){
	             RobotIanus robotI = new RobotIanus();

	             if(pantallas != 1){ pantallas = 4;}
	             robotI.robotIanus(cadena, 1000, pantallas, 1, "",false,false);
	             
		            if(InicioIanus.numeroIanus==1 || !InicioIanus.par){
			            VentanaExplorador.numArchivo++;
			            int tamañoLista = VentanaExplorador.listaPdfs.getModel().getSize();
			            if(VentanaExplorador.numArchivo<tamañoLista){
			            	VentanaExplorador.listaPdfs.setSelectedIndex(VentanaExplorador.numArchivo);
			            	
			        		int pdfNumero = VentanaExplorador.listaPdfs.getSelectedIndex();
			 
			        		File archivo = new File(InicioIanus.rutaCompletaPdfs[VentanaExplorador.numArchivo]);
			        		try{
//			        			Desktop.getDesktop().open(archivo);
			        			Robot robot = new Robot();
			        			robot.delay(400);
			       			    Process p = Runtime.getRuntime()
		    					        .exec("rundll32 url.dll,FileProtocolHandler " + archivo);		        			
			       			    // Coloca cursor sobre aceptar
			        			robot.mouseMove(1504, 706);
			        		}catch (Exception ev) {
			        			System.out.println(ev);
			        		}
			            }
			            if(InicioIanus.numeroIanus == 2){
			            	VentanaExplorador.numArchivo++;
				            if(VentanaExplorador.numArchivo<tamañoLista){
				            	VentanaExplorador.listaPdfs.setSelectedIndex(VentanaExplorador.numArchivo);
				            	
				        		int pdfNumero = VentanaExplorador.listaPdfs.getSelectedIndex();
				 
				        		File archivo = new File(InicioIanus.rutaCompletaPdfs[VentanaExplorador.numArchivo]);
				        		try{
//				        			Desktop.getDesktop().open(archivo);
			            			Robot robot = new Robot();
			            			robot.delay(400);
				        			Process p = Runtime.getRuntime()
			    					        .exec("rundll32 url.dll,FileProtocolHandler " + archivo);			        			
			

			            			robot.delay(400);
			            			//	Ajusta los documentos horizontalmente

			        				robot.keyPress(KeyEvent.VK_CONTROL);
			        				robot.keyPress(KeyEvent.VK_SHIFT);
			        				robot.keyPress(KeyEvent.VK_K);
			        				robot.keyRelease(KeyEvent.VK_K);
			        				robot.keyRelease(KeyEvent.VK_SHIFT);
			        				robot.keyRelease(KeyEvent.VK_CONTROL);
					         			
				        		}catch (Exception ev) {
				        			System.out.println(ev);
				        		}		            	
				            }
			            }
	        			
		            }
	             
	             
	             
	             
	        }
/*
	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        .setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
	            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
	            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
	            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
	            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
	        );
	 */       
	        // pack();

	        
	        
	    // </editor-fold>

	    /**
	     * @param args the command line arguments
	     */

	    // Variables declaration - do not modify
	    private javax.swing.JButton jButton1;
	    private JButton jButton2;
	    private JButton jButton3;
	    private JPanel panel;
	    private JPanel panelN;
	    // End of variables declaration
	}
	
	
	

