import java.awt.AWTException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Robot;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;

import javax.swing.ActionMap;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.KeyStroke;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Coco
 */
public class VentanaBotonesDocMini extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBotones
     */
	int pantallas;
	JRadioButton jRBmini;

	
	JComboBox comboVentanas = new javax.swing.JComboBox();
	
    public VentanaBotonesDocMini() {
    	pantallas = InicioIanus.numeroPantallas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

    	jPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        // jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        InicioIanus.teclaAzul1 = new javax.swing.JButton();
        InicioIanus.teclaAzul2 = new javax.swing.JButton();
        
        Dimension mini = new Dimension(170,30);
        final Dimension dimComboBox = new Dimension(80,15);
        final Dimension micro = new Dimension(150,18);
        final Dimension normal = new Dimension(190,60);
        
        final Font microFont = new java.awt.Font("Serif", 1, 11);
        final Font normalFont = new java.awt.Font("Serif", 1, 18);
        
        /*********************/
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBackground(new Color(255,228,225)); 
        
     //   this.setUndecorated(true);
		 
        InicioIanus.jButtonTeclas = new javax.swing.JButton("Teclas Habilitadas");
        InicioIanus.jButtonTeclas.setMinimumSize(micro);
        InicioIanus.jButtonTeclas.setMaximumSize(micro);
        InicioIanus.jButtonTeclas.setPreferredSize(micro);
        InicioIanus.jButtonTeclas.setBackground(new Color(127,255,212));
        InicioIanus.jButtonTeclas.setToolTipText("Activa / Desactiva las teclas rápidas");
        
        jButtonAzules = new javax.swing.JButton("Botones Azules Fijados");
        jButtonAzules.setMinimumSize(micro);
        jButtonAzules.setMaximumSize(micro);
        jButtonAzules.setPreferredSize(micro);
        jButtonAzules.setBackground(new Color(191,239,255));
        jButtonAzules.setToolTipText("Editables: Pulsar sobre cualquier nombre normalizado, para añadirlo como nombre a los botones azules" );
        if(InicioIanus.documentacion == 2 || InicioIanus.documentacion == 3){
        	jButtonAzules.setEnabled(false);
        }
        
        comboVentanas.addItem("Normal");
        comboVentanas.addItem("Mini");
        comboVentanas.addItem("Micro1");
        comboVentanas.addItem("Micro2");
        comboVentanas.addItem("Micro3");

        //comboVentanas.setSelectedIndex(0);
        comboVentanas.setMaximumSize(dimComboBox);
        comboVentanas.setMinimumSize(dimComboBox);
        comboVentanas.setPreferredSize(dimComboBox);
        comboVentanas.setBackground(Color.white);
        
        comboVentanas.setSelectedItem(InicioIanus.ventanaBotonesTeclaAtributo);
        if(InicioIanus.documentacion == 2 || InicioIanus.documentacion == 3){
        	comboVentanas.setSelectedItem("Micro1");
        	System.out.println("Seleccionamos micro");
        }
        
        
        
        jRBmini = new JRadioButton("Mini");
          
         
  /*      jRBmini.setText("Ampliar Ventana");
        jRBmini.setSelected(true);
        jRBmini.setMinimumSize(dimComboBox);
        jRBmini.setMaximumSize(dimComboBox);
        jRBmini.setPreferredSize(dimComboBox);
        jRBmini.setBackground(new Color(255,228,225)); 
        jRBmini   */
        
        comboVentanas.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				
				if (comboVentanas.getSelectedItem().toString().equals("Mini")){
					InicioIanus.ventanaBotonesTeclaAtributo = "Mini";
					redimensionar(micro, microFont, comboVentanas.getSelectedItem().toString());
					
					jPanel2.add(InicioIanus.jButtonTeclas);
			        jPanel2.add(jButtonAzules);
			        jPanel2.add(comboVentanas);
			        jPanel2.setVisible(true);
					
					javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
			        jPanel1.setLayout(jPanel1Layout);
			        jPanel1Layout.setHorizontalGroup(
			            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			            .addGroup(jPanel1Layout.createSequentialGroup()
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
			                    .addGroup(jPanel1Layout.createSequentialGroup()
			                        .addComponent(jButton12)
			                        .addComponent(jButton13)
			                        .addComponent(InicioIanus.teclaAzul1)
			                        .addComponent(InicioIanus.teclaAzul2))
			                    .addGroup(jPanel1Layout.createSequentialGroup()
			                        .addComponent(jButton1)
			                        .addComponent(jButton9)
			                        .addComponent(jButton10)
			                        .addComponent(InicioIanus.jBultimoNombreSubido )))));
			        jPanel1Layout.setVerticalGroup(
			            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			            .addGroup(jPanel1Layout.createSequentialGroup()
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, /*40*/15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.jBultimoNombreSubido , javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.teclaAzul1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.teclaAzul2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))));
			        pack();
				}else if(comboVentanas.getSelectedItem().toString().equals("Normal")){
					InicioIanus.ventanaBotonesTeclaAtributo = "Normal";
					redimensionar(normal, normalFont, comboVentanas.getSelectedItem().toString());
					
					setResizable(true);
					setSize(new java.awt.Dimension(770, 180));
					
					jPanel2.add(InicioIanus.jButtonTeclas);
			        jPanel2.add(jButtonAzules);
			        jPanel2.add(comboVentanas);
			        jPanel2.setVisible(true);
					
			        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
			        jPanel1.setBackground(Color.white);
			        jPanel1.setLayout(jPanel1Layout);
			        jPanel1Layout.setHorizontalGroup(
			            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			            .addGroup(jPanel1Layout.createSequentialGroup()
			                .addGap(2)
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
			                    .addGroup(jPanel1Layout.createSequentialGroup()
			                        .addComponent(jButton12)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(jButton13)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(InicioIanus.teclaAzul1)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(InicioIanus.teclaAzul2))
			                    .addGroup(jPanel1Layout.createSequentialGroup()
			                        .addComponent(jButton1)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(jButton9)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(jButton10)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(InicioIanus.jBultimoNombreSubido )))
			                .addContainerGap(129, Short.MAX_VALUE))
			        );
			        jPanel1Layout.setVerticalGroup(
			            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			            .addGroup(jPanel1Layout.createSequentialGroup()
			                .addGap(2)
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.jBultimoNombreSubido , javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
			                .addGap(2)
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.teclaAzul1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.teclaAzul2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
			                .addContainerGap(250, Short.MAX_VALUE))
			        );
			        pack();
				}
				else if(comboVentanas.getSelectedItem().toString().equals("Micro1")){
					InicioIanus.ventanaBotonesTeclaAtributo = "Micro1";
					redimensionar(normal, normalFont, comboVentanas.getSelectedItem().toString());
					
					setResizable(true);
					setSize(new java.awt.Dimension(770, 180));
					
					jPanel2.add(InicioIanus.jButtonTeclas);
			        jPanel2.add(jButtonAzules);
			        jPanel2.add(comboVentanas);
			        jPanel2.setVisible(true);
					
			        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
			        jPanel1.setBackground(Color.white);
			        jPanel1.setLayout(jPanel1Layout);
			        jPanel1Layout.setHorizontalGroup(
			            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			            .addGroup(jPanel1Layout.createSequentialGroup()
			                .addGap(2)
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
			                    .addGroup(jPanel1Layout.createSequentialGroup()
			                        .addComponent(jButton12)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(jButton13)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(InicioIanus.teclaAzul1)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(InicioIanus.teclaAzul2))
			                    .addGroup(jPanel1Layout.createSequentialGroup()
			                        .addComponent(jButton1)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(jButton9)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(jButton10)
			                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			                        .addComponent(InicioIanus.jBultimoNombreSubido )))
			                .addContainerGap(129, Short.MAX_VALUE))
			        );
			        jPanel1Layout.setVerticalGroup(
			            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			            .addGroup(jPanel1Layout.createSequentialGroup()
			                .addGap(2)
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.jBultimoNombreSubido , javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
			                .addGap(2)
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.teclaAzul1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.teclaAzul2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
			                .addContainerGap(250, Short.MAX_VALUE))
			        );
			        pack();
				}
				else if(comboVentanas.getSelectedItem().toString().equals("Micro2")){
					InicioIanus.ventanaBotonesTeclaAtributo = "Micro2";
					redimensionar(micro, microFont, comboVentanas.getSelectedItem().toString());
					
					setResizable(true);
					setSize(new java.awt.Dimension(770, 180));
					
					jPanel2.add(InicioIanus.jButtonTeclas);
			        jPanel2.add(jButtonAzules);
			        jPanel2.add(comboVentanas);
			        jPanel2.setVisible(true);
					
					javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
			        jPanel1.setLayout(jPanel1Layout);
			        jPanel1Layout.setHorizontalGroup(
			            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			            .addGroup(jPanel1Layout.createSequentialGroup()
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
			                    .addGroup(jPanel1Layout.createSequentialGroup()
			                        .addComponent(jButton12)
			                        .addComponent(jButton13)
			                        .addComponent(InicioIanus.teclaAzul1)
			                        .addComponent(InicioIanus.teclaAzul2)
			                        .addComponent(InicioIanus.jBultimoNombreSubido ))
			                    .addGroup(jPanel1Layout.createSequentialGroup()
			                        .addComponent(jButton1)
			                        .addComponent(jButton9)
			                        .addComponent(jButton10)))));
			        jPanel1Layout.setVerticalGroup(
			            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			            .addGroup(jPanel1Layout.createSequentialGroup()
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, /*40*/15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.teclaAzul1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.teclaAzul2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.jBultimoNombreSubido , javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))));
			        pack();
				}
				else if(comboVentanas.getSelectedItem().toString().equals("Micro3")){
					InicioIanus.ventanaBotonesTeclaAtributo = "Micro3";
					redimensionar(micro, microFont, comboVentanas.getSelectedItem().toString());
					
					setResizable(true);
					setSize(new java.awt.Dimension(770, 180));
					
					javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
			        jPanel1.setLayout(jPanel1Layout);
			        jPanel1Layout.setHorizontalGroup(
			            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			            .addGroup(jPanel1Layout.createSequentialGroup()
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
			                    .addGroup(jPanel1Layout.createSequentialGroup()
				                    .addComponent(InicioIanus.jButtonTeclas)
				                    .addComponent(jButtonAzules)
				                    .addGap(3)
			                        .addComponent(comboVentanas)
			                        .addGap(3)
			                        .addComponent(jButton12)
			                        .addComponent(jButton13)
			                        .addComponent(InicioIanus.teclaAzul1)
			                        .addComponent(InicioIanus.teclaAzul2)
			                        .addComponent(InicioIanus.jBultimoNombreSubido ))
			                    .addGroup(jPanel1Layout.createSequentialGroup()
			                        .addComponent(jButton1)
			                        .addComponent(jButton9)
			                        .addComponent(jButton10)))));
			        jPanel1Layout.setVerticalGroup(
			            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			            .addGroup(jPanel1Layout.createSequentialGroup()
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, /*40*/15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
			                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
			                	.addGap(3)
			                	.addComponent(InicioIanus.jButtonTeclas)
			                    .addComponent(jButtonAzules)
			                    .addComponent(comboVentanas)
			                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.teclaAzul1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.teclaAzul2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
			                    .addComponent(InicioIanus.jBultimoNombreSubido , javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)


			                    )));
			        pack();
			        }
				jPanel.requestFocus();
			}
			
        });
        
        jPanel2.add(InicioIanus.jButtonTeclas);
        jPanel2.add(jButtonAzules);
        jPanel2.add(comboVentanas);
   /*     jPanel2.add(jRBmini);
        jPanel2.add(jRBmicro1);
        jPanel2.add(jRBmicro2);
        jPanel2.add(jRBnormal); */
        
        
        /************/
        
        InicioIanus.jBultimoNombreSubido = new javax.swing.JButton();
        
        String b1, b2, b3;
        
        if(InicioIanus.documentacion != 0 && InicioIanus.documentacion != 3){
          	b1 = "Inclusion l.e.";
            b2 = "Interconsulta";
            b3 = "Consentimento informado";
        }else{
        	b1 = "Informe urg.";
            b2 = "Enfermería urg.";
            b3 = "URG";
        }
        
        String b4 = "Último doc.";
        String b5 = "EKG";
        String b6 = "Eco";
        
        String b7;
        String b8;
        if(InicioIanus.documentacion == 2 || InicioIanus.documentacion == 3){
        	b7 = "NHC";
            b8 = "Documento";
        }else{
            b7 = "Editable 1";
            b8 = "Editable 2";
        }

        String b9 = "Doc. anulado";
        
        
     //   InicioIanus.documentosServicio. 
        
        InicioIanus.excel.getDocServicio(InicioIanus.servicioCombo);
        
        
        setTitle("Teclas Rápidas");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(610, 85));
        setResizable(true);

        File archivo2, archivo3;
        
    	archivo3 = new File("cal\\ianus.exe");
        if (InicioIanus.documentacion != 2 && InicioIanus.documentacion != 3){
        	archivo2 = new File("cal\\TeclasRapidas.exe");
        }
        else{
        	archivo2 = new File("cal\\TeclasExperimental.exe");
        }
        try {
			Process p = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + archivo2);
			if(InicioIanus.documentacion == 2 || InicioIanus.documentacion == 3){
				Process pianus = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + archivo3);
			}
			
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
        
        
        jButton1.setBackground(new java.awt.Color(144,238,144));
        jButton1.setMaximumSize(micro);
        jButton1.setMinimumSize(micro);
        jButton1.setPreferredSize(micro);
        jButton1.setFont(microFont);
        jButton1.setText(b1);
        
        jButton1.addMouseListener(new MouseListener() {
         	 public void mouseClicked(MouseEvent evt)
         	 {
         		if (evt.getButton()==java.awt.event.MouseEvent.BUTTON3){
         			abrirAutoHotKey();
         			 JOptionPane.showMessageDialog(jButton1, "Teclas rápidas habilitadas");
             	}
             	else{
             		imprime(jButton1.getText(),false,0);
             		jPanel.requestFocus();
             		}
         	 }

  			@Override
  			public void mouseEntered(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mouseExited(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mousePressed(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mouseReleased(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}
         });

        jButton9.setBackground(new java.awt.Color(144,238,144));
        jButton9.setMaximumSize(micro);
        jButton9.setMinimumSize(micro);
        jButton9.setPreferredSize(micro);
        jButton9.setFont(microFont);
        jButton9.setText(b2);
        
        jButton9.addMouseListener(new MouseListener() {
         	 public void mouseClicked(MouseEvent evt)
         	 {
         		if (evt.getButton()==java.awt.event.MouseEvent.BUTTON3){
         			/* Object seleccion = JOptionPane.showInputDialog(InicioIanus.teclaAzul2,"Seleccione el Documento","Selector de documentos",JOptionPane.QUESTION_MESSAGE,
   		        		   null, // unIcono,  // null para icono defecto
   		        		   new Object[] { "opcion 1", "opcion 2", "opcion 3" }, 
   		        		   "opcion 1");
   		        		   */
             	}
             	else{
             		imprime(jButton9.getText(),false,0);
             		jPanel.requestFocus();
             		}
         	 }

  			@Override
  			public void mouseEntered(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mouseExited(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mousePressed(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mouseReleased(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}
         });

        jButton10.setBackground(new java.awt.Color(144,238,144));
        jButton10.setMaximumSize(micro);
        jButton10.setMinimumSize(micro);
        jButton10.setPreferredSize(micro);
        jButton10.setFont(microFont);
        jButton10.setText(b3);
        
        jButton10.addMouseListener(new MouseListener() {
         	 public void mouseClicked(MouseEvent evt)
         	 {
         		if (evt.getButton()==java.awt.event.MouseEvent.BUTTON3){
         			/* Object seleccion = JOptionPane.showInputDialog(InicioIanus.teclaAzul2,"Seleccione el Documento","Selector de documentos",JOptionPane.QUESTION_MESSAGE,
   		        		   null, // unIcono,  // null para icono defecto
   		        		   new Object[] { "opcion 1", "opcion 2", "opcion 3" }, 
   		        		   "opcion 1");
   		        		   */
             	}
             	else{
             		imprime(jButton10.getText(),false,0);
             		jPanel.requestFocus();
             		}
         	 }

  			@Override
  			public void mouseEntered(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mouseExited(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mousePressed(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mouseReleased(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}
         });

        InicioIanus.jBultimoNombreSubido .setBackground(new java.awt.Color(255, 51, 51));
        InicioIanus.jBultimoNombreSubido .setMaximumSize(micro);
        InicioIanus.jBultimoNombreSubido .setMinimumSize(micro);
        InicioIanus.jBultimoNombreSubido .setPreferredSize(micro);
        InicioIanus.jBultimoNombreSubido .setFont(microFont);
        InicioIanus.jBultimoNombreSubido .setText(b4);
        
        InicioIanus.jBultimoNombreSubido .addMouseListener(new MouseListener() {
         	 public void mouseClicked(MouseEvent evt)
         	 {
         		if (evt.getButton()==java.awt.event.MouseEvent.BUTTON3){
         			cerrarAutoHotKey(false);
          			 JOptionPane.showMessageDialog(InicioIanus.jBultimoNombreSubido, "Teclas rápidas deshabilitadas");
           			
               	}
             	else{
             		imprime(InicioIanus.jBultimoNombreSubido .getText(),false,0);
             		jPanel.requestFocus();
             		}
         	 }

  			@Override
  			public void mouseEntered(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mouseExited(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mousePressed(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mouseReleased(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}
         });

        jButton12.setBackground(new java.awt.Color(255, 255, 51));
        jButton12.setMaximumSize(micro);
        jButton12.setMinimumSize(micro);
        jButton12.setPreferredSize(micro);
        jButton12.setFont(microFont);
        jButton12.setText(b5);
        
        jButton12.addMouseListener(new MouseListener() {
         	 public void mouseClicked(MouseEvent evt)
         	 {
         		if (evt.getButton()==java.awt.event.MouseEvent.BUTTON3){
         			/* Object seleccion = JOptionPane.showInputDialog(InicioIanus.teclaAzul2,"Seleccione el Documento","Selector de documentos",JOptionPane.QUESTION_MESSAGE,
   		        		   null, // unIcono,  // null para icono defecto
   		        		   new Object[] { "opcion 1", "opcion 2", "opcion 3" }, 
   		        		   "opcion 1");
   		        		   */
             	}
             	else{
             		imprime(jButton12.getText(),false,0);
             		jPanel.requestFocus();
             		}
         	 }

  			@Override
  			public void mouseEntered(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mouseExited(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mousePressed(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}

  			@Override
  			public void mouseReleased(MouseEvent arg0) {
  				// TODO Auto-generated method stub
  				
  			}
         });
        

        jButton13.setBackground(new java.awt.Color(255, 255, 51));
        jButton13.setMaximumSize(micro);
        jButton13.setMinimumSize(micro);
        jButton13.setPreferredSize(micro);
        jButton13.setFont(microFont);
        jButton13.setText(b6);
        
        jButton13.addMouseListener(new MouseListener() {
          	 public void mouseClicked(MouseEvent evt)
          	 {
          		if (evt.getButton()==java.awt.event.MouseEvent.BUTTON3){
          			/* Object seleccion = JOptionPane.showInputDialog(InicioIanus.teclaAzul2,"Seleccione el Documento","Selector de documentos",JOptionPane.QUESTION_MESSAGE,
    		        		   null, // unIcono,  // null para icono defecto
    		        		   new Object[] { "opcion 1", "opcion 2", "opcion 3" }, 
    		        		   "opcion 1");
    		        		   */
              	}
              	else{
              		imprime(jButton13.getText(),false,0);
              		jPanel.requestFocus();
              		}
          	 }

   			@Override
   			public void mouseEntered(MouseEvent arg0) {
   				// TODO Auto-generated method stub
   				
   			}

   			@Override
   			public void mouseExited(MouseEvent arg0) {
   				// TODO Auto-generated method stub
   				
   			}

   			@Override
   			public void mousePressed(MouseEvent arg0) {
   				// TODO Auto-generated method stub
   				
   			}

   			@Override
   			public void mouseReleased(MouseEvent arg0) {
   				// TODO Auto-generated method stub
   				
   			}
          });
        

        InicioIanus.teclaAzul1.setBackground(new java.awt.Color(175,238,238));
        InicioIanus.teclaAzul1.setMaximumSize(micro);
        InicioIanus.teclaAzul1.setMinimumSize(micro);
        InicioIanus.teclaAzul1.setPreferredSize(micro);
        InicioIanus.teclaAzul1.setFont(microFont);
        InicioIanus.teclaAzul1.setText(b7);
        
        InicioIanus.teclaAzul1.addMouseListener(new MouseListener() {
       	 public void mouseClicked(MouseEvent evt)
       	 {
       		if(InicioIanus.documentacion != 2 && InicioIanus.documentacion != 3){	
       		 	if (evt.getButton()==java.awt.event.MouseEvent.BUTTON3){
	       			 
	       			InicioIanus.excel.getDocServicio(InicioIanus.servicioCombo);
	       			
	       			Object[] objetosDocumentos = InicioIanus.documentosServicio.toArray();
	       			
	       			Object seleccion = JOptionPane.showInputDialog(InicioIanus.teclaAzul2,"Seleccione el Documento","Selector de documentos",JOptionPane.QUESTION_MESSAGE,
	 		        		   null, // unIcono,  // null para icono defecto
	 		        		   objetosDocumentos, 
	 		        		   objetosDocumentos[0]);
	       			
	       			InicioIanus.teclaAzul1.setText(seleccion.toString());
	           	}
	           	else{
	           		imprime(InicioIanus.teclaAzul1.getText(),false,0);
	           		jPanel.requestFocus();
	           	}
	       	}
	       	else{
	       		introduceNHC();
	       		jPanel.requestFocus();
	       	}
       	 }

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}
       });
        

        InicioIanus.teclaAzul2.setBackground(new java.awt.Color(175,238,238));
        InicioIanus.teclaAzul2.setMaximumSize(micro);
        InicioIanus.teclaAzul2.setMinimumSize(micro);
        InicioIanus.teclaAzul2.setPreferredSize(micro);
        InicioIanus.teclaAzul2.setFont(microFont);
        InicioIanus.teclaAzul2.setText(b8);
           
        InicioIanus.teclaAzul2.addMouseListener(new MouseListener() {
        	 public void mouseClicked(MouseEvent evt)
        	 {
        		 if(InicioIanus.documentacion != 2 && InicioIanus.documentacion != 3){	
         		 	if (evt.getButton()==java.awt.event.MouseEvent.BUTTON3){
 	        			
 	        			Object[] objetosDocumentos = InicioIanus.documentosServicio.toArray();
 	           			
 	           			Object seleccion = JOptionPane.showInputDialog(InicioIanus.teclaAzul2,"Seleccione el Documento","Selector de documentos",JOptionPane.QUESTION_MESSAGE,
 	     		        		   null, // unIcono,  // null para icono defecto
 	     		        		   objetosDocumentos, 
 	     		        		   objetosDocumentos[0]);
 	           			InicioIanus.teclaAzul2.setText(seleccion.toString());
 	            	}
 	            	else{
 	            		 imprime(InicioIanus.teclaAzul2.getText(),false,0);
 	            		 jPanel.requestFocus();
 	            	}
 	        	}
 	        	else{
 	        		imprime(InicioIanus.teclaAzul2.getText(),false,0);
 	        		jPanel.requestFocus();
 	        	}
        	 }

			@Override
			public void mouseEntered(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
				// TODO Auto-generated method stub
				
			}
        });
 
        InicioIanus.jButtonTeclas.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				if (InicioIanus.jButtonTeclas.getText().contains("Teclas Habilitadas")){
					cerrarAutoHotKey(false);
					jPanel1.requestFocus();
				}else{
					abrirAutoHotKey();
					jPanel.requestFocus();
				}
			}
        	
        });
        
        jButtonAzules.addActionListener(new ActionListener(){

  			@Override
  			public void actionPerformed(ActionEvent arg0) {
  				// TODO Auto-generated method stub
  				if(InicioIanus.documentacion != 2 && InicioIanus.documentacion != 3){
	  				if (jButtonAzules.getText().contains("Botones Azules Editables")){
	  					InicioIanus.teclasAzulesEditables = false;
	  					jButtonAzules.setText("Botones Azules Fijados");
	  					jButtonAzules.setBackground(new Color(191,239,255));
	  					jPanel.requestFocus();
	  				}else{
	  					InicioIanus.teclasAzulesEditables = true;
	  					jButtonAzules.setText("Botones Azules Editables");
	  					jButtonAzules.setBackground(new Color(000,191,255));
	  					jPanel.requestFocus();
	  				}
  				}
  			}
          	
          });
        
        
        KeyListener listener = new KeyListener() {
			@Override
			public void keyTyped(KeyEvent e) {
				System.out.println("keyTyped="+KeyEvent.getKeyText(e.getKeyCode()));
			}

			@Override
			public void keyPressed(KeyEvent e) {
				System.out.println("keyPressed="+KeyEvent.getKeyText(e.getKeyCode()));
			}

			@Override
			public void keyReleased(KeyEvent e) {
				
				if(!InicioIanus.suspensionTeclado){
					switch (e.getKeyCode()){
					case KeyEvent.VK_A: imprime(jButton1.getText(),false,0);break;
					// case KeyEvent.VK_F1:imprime(jButton1.getText(),false,0);break;
					case KeyEvent.VK_S: imprime(jButton9.getText(),false,0);break;
					// case KeyEvent.VK_F2:imprime(jButton9.getText(),false,0);break;
					case KeyEvent.VK_D: imprime(jButton10.getText(),false,0);break;
					// case KeyEvent.VK_F3:imprime(jButton10.getText(),false,0);break;
					case KeyEvent.VK_F: imprime(InicioIanus.jBultimoNombreSubido .getText(),false,0);break;
					// case KeyEvent.VK_F4:imprime(InicioIanus.jBultimoNombreSubido .getText(),false,0);break;
					case KeyEvent.VK_Z: imprime(jButton12.getText(),false,0);break;
					// case KeyEvent.VK_F5:imprime(jButton12.getText(),false,0);break;
					case KeyEvent.VK_X: imprime(jButton13.getText(),false,0);break;
					//case KeyEvent.VK_F6:imprime(jButton13.getText());break;
					//case KeyEvent.VK_SPACE: alternarPdf();break;
					//case KeyEvent.VK_F7: break;
					
					
					case KeyEvent.VK_F1: 
						//	Fuerza a que lo imprima como ingreso
						if(InicioIanus.documentacion == 2 || InicioIanus.documentacion == 3){
							InicioIanus.nodoForzado = true;
							imprime(InicioIanus.teclaAzul2.getText(), false, 1);
							InicioIanus.nodoForzado = false;
						}
						break;
					case KeyEvent.VK_F2: 
						//	Fuerza a que lo imprima como consulta
						if(InicioIanus.documentacion == 2 || InicioIanus.documentacion == 3){
							InicioIanus.nodoForzado = true;
							imprime(InicioIanus.teclaAzul2.getText(), false, 2);
							InicioIanus.nodoForzado = false;
						}
						break;
					case KeyEvent.VK_F3: 
						//	Fuerza a que lo imprima como cia
						if(InicioIanus.documentacion == 2 || InicioIanus.documentacion == 3){
							InicioIanus.nodoForzado = true;
							imprime(InicioIanus.teclaAzul2.getText(), false, 3);
							InicioIanus.nodoForzado = false;
						}
						break;
					
					
					case KeyEvent.VK_C: 
						if(InicioIanus.documentacion != 2 && InicioIanus.documentacion != 3){
							//System.out.println("Estoy pulsando la c");
							imprime(InicioIanus.teclaAzul1.getText(),false,0);break;
						}
						else{
							introduceNHC();
							InicioIanus.subidaExtrema = true;
						}
						break;
					//case KeyEvent.VK_F8: break;
					case KeyEvent.VK_V: 
						if(InicioIanus.documentacion != 2 && InicioIanus.documentacion != 3){
							//System.out.println("Estoy pulsando la v");
							imprime(InicioIanus.teclaAzul2.getText(),false,0);
						}
						else{
							imprime(InicioIanus.teclaAzul2.getText(),false,0);
							System.out.println("Imprimiendo");
							//imprimeNombreDoc();
						}
						break;
					case KeyEvent.VK_ESCAPE: cerrarAutoHotKey(false);break;
					case KeyEvent.VK_SPACE: 

						InicioIanus.ClickImportante = InicioIanus.ultimoClick;
						
						if((InicioIanus.documentacion == 2 && InicioIanus.ocr2IanusAutomatico) || (InicioIanus.documentacion == 3 && InicioIanus.ocr2IanusAutomatico)){
							InicioIanus.gestion2ianus.gestion();
						}

						else if(InicioIanus.documentacion == 2 || InicioIanus.documentacion == 3){
							

							
							if(InicioIanus.documentos[InicioIanus.pdfSeleccionado].nhc.equals(InicioIanus.documentos[InicioIanus.pdfSeleccionado-1].nhc)
									&& /* (!InicioIanus.documentos[InicioIanus.pdfSeleccionado].servicio.equals("DIG")  && */ !InicioIanus.documentos[InicioIanus.pdfSeleccionado].servicio.equals("ALG")){
								 // JOptionPane.showMessageDialog(null, "En principio es el mismo paciente");
								 //	InicioIanus.tipoSubida = 1;
								 if(new GestionServicioPuntero().gestion()){
									 imprime(InicioIanus.teclaAzul2.getText(),true,0);
								 }
									 
							 }
							else{
								pulsaTecla(KeyEvent.VK_F9);   // Es la tecla para salir del paciente en ianus
								
								
								//JOptionPane.showMessageDialog(null, "Debería imprimir " + InicioIanus.ocrTurbo);
								if(InicioIanus.tipoSubida != 0  && !InicioIanus.teclaAzul1.getText().equals("Separador") 
										 /* && 	VentanaExplorador.numArchivo + 1 <  VentanaExplorador.listaPdfs.getModel().getSize()  */  ){
									retardo(800);
									
									introduceNHC();
									// InicioIanus.subidaExtrema = true;
								}
							}
						}
						else{
							pulsaTecla(KeyEvent.VK_F9);   // Es la tecla para salir del paciente en ianus
							
							//JOptionPane.showMessageDialog(null, "Debería imprimir " + InicioIanus.ocrTurbo);
							/*
							 * if(InicioIanus.documentacion == 2 && InicioIanus.ocrTurbo && !InicioIanus.teclaAzul1.getText().equals("Separador")){
								retardo(800);
								
								introduceNHC();
							}
							*/
						}
											
						break;
					}
				}

				
			//	if(e.getKeyCode() == KeyEvent.VK_A )
					
			//	 System.out.println("keyReleased="+KeyEvent.getKeyText(e.getKeyCode()));
				jPanel.requestFocus();
			}
		};
		jPanel.addKeyListener(listener);
		jPanel.setFocusable(true);
        
        
  
		redimensionar(normal, normalFont, "Normal");
		
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setBackground(Color.white);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InicioIanus.teclaAzul1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InicioIanus.teclaAzul2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InicioIanus.jBultimoNombreSubido )))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InicioIanus.jBultimoNombreSubido , javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InicioIanus.teclaAzul1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InicioIanus.teclaAzul2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        pack();
        
        
/*
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
*/
       jPanel.setLayout(new BorderLayout());
       jPanel.add(jPanel2, BorderLayout.NORTH);
       jPanel.add(jPanel1, BorderLayout.CENTER);
       setContentPane(jPanel);
        
        
        
        pack();
        this.setVisible(true);
        
        
        
      //  abrirAutoHotKey();
    }// </editor-fold>

    
    public void pulsaTecla(int tecla){
    	try {
			Robot robot = new Robot();
			robot.keyPress(/*KeyEvent.VK_F9*/ tecla);
			robot.keyRelease(/*KeyEvent.VK_F9*/ tecla);
			robot.delay(200);
						
		} catch (AWTException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    }
    
    public void retardo(int tiempo){
		try {
			Robot robot = new Robot();
			robot.delay(tiempo);
			
		} catch (AWTException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
    
    public void introduceNHC(){
    	try {
			Robot robot = new Robot();
			robot.keyPress(KeyEvent.VK_F10);
			robot.keyRelease(KeyEvent.VK_F10);
			robot.delay(200);
			
			CopEnPortapapeles copiar = new CopEnPortapapeles();
			copiar.copiarAlPortapapeles(InicioIanus.teclaAzul1.getText());
			
			robot.keyPress(KeyEvent.VK_CONTROL);
			robot.keyPress(KeyEvent.VK_V);
			robot.keyRelease(KeyEvent.VK_V);
			robot.keyRelease(KeyEvent.VK_CONTROL);
			robot.delay(100);
			
			robot.keyPress(KeyEvent.VK_ENTER);
			robot.keyRelease(KeyEvent.VK_ENTER);
			robot.delay(100);
			
			
		} catch (AWTException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    }
 
    public void imprimeNombreDoc(){
    	
    }   

  
    
    
/**********************************************   Nueva Version  *****************/
    
    public void imprime(String cadena, boolean pulsadaBarraEspaciadora, int tipoDocAsubirForzado){
		Impresion impr = new Impresion();
		impr.imprime(cadena,pulsadaBarraEspaciadora,tipoDocAsubirForzado);
	}
    
    
    public void alternarPdf(){
    	if (InicioIanus.numPdfsAbiertos == 2){
    		File comodin = InicioIanus.tandaDePdfs[0];
    		InicioIanus.tandaDePdfs[0] = InicioIanus.tandaDePdfs[1];
    		InicioIanus.tandaDePdfs[1] = comodin;
    		if(!InicioIanus.pdfsAlternados){
	    		Inicio.navegador2.webBrowserPanel.setBackground(new Color(80,200,120));
	    		Inicio.navegador1.webBrowserPanel.setBackground(new Color(255,246,143));
	    		InicioIanus.pdfsAlternados = true;
    		}
    		else{
    			Inicio.navegador1.webBrowserPanel.setBackground(new Color(80,200,120));
	    		Inicio.navegador2.webBrowserPanel.setBackground(new Color(255,246,143));
	    		InicioIanus.pdfsAlternados = false;
    		}
    	}
    }
    
    

    public void cerrarAutoHotKey(boolean matarTodo){
    	
    	try {
			Robot robot = new Robot();
			robot.keyPress(KeyEvent.VK_F6);
			robot.keyRelease(KeyEvent.VK_F6);
			robot.delay(100);
			
		} catch (AWTException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    	String cmd = "taskkill.exe /F /IM ianus.exe /T";
		String cmd2 = "taskkill.exe /F /IM TeclasExperimental.exe /T";
		String cmd3 = "taskkill.exe /F /IM TeclasRapidas.exe /T";
    	
		
		Process hijo, hijo2, hijo3;
    	try {
    		
    		
    		
    		
    		/*
			Robot robot = new Robot();
			robot.keyPress(KeyEvent.VK_ESCAPE);
			robot.keyRelease(KeyEvent.VK_ESCAPE);
			robot.delay(100);
			
			robot.keyPress(KeyEvent.VK_ESCAPE);
			robot.keyRelease(KeyEvent.VK_ESCAPE);
			robot.delay(100);
			
			robot.keyPress(KeyEvent.VK_ESCAPE);
			robot.keyRelease(KeyEvent.VK_ESCAPE);
			robot.delay(100);
			
			*/
    		
    		
			hijo2 = Runtime.getRuntime().exec(cmd2);
			hijo3 = Runtime.getRuntime().exec(cmd3);
			
			
			
			hijo2.waitFor();
			hijo3.waitFor();
			
			if(matarTodo){
				hijo = Runtime.getRuntime().exec(cmd);
				hijo.waitFor();
			}
			
			Thread.sleep(300);
				
				InicioIanus.jButtonTeclas.setBackground(new Color(255,106,106));
		    	InicioIanus.jButtonTeclas.setText("Teclas Deshabilitadas");
				
			} catch (IOException e) {
				System.out.println("Incapaz de matar.");
			} catch (InterruptedException e) {
				System.out.println("Incapaz de matar.");
		}
 	
     }
     
     public void abrirAutoHotKey(){
    	 File archivo2;
    	 
    	 
    	 // File archivo3 = new File("cal\\ianus.exe");
    	 
    	 if(InicioIanus.documentacion != 2 && InicioIanus.documentacion != 3){
    		  archivo2 = new File("cal\\TeclasRapidas.exe");
    	 }
    	 else{
    		 archivo2 = new File("cal\\TeclasExperimental.exe");
    	 }
         
         try {
 			Process p = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + archivo2);
 			
 			InicioIanus.jButtonTeclas.setBackground(new Color(127,255,212));
	    	InicioIanus.jButtonTeclas.setText("Teclas Habilitadas");  
	    	
	    	/*
			if(InicioIanus.documentacion == 2 || InicioIanus.documentacion == 3){
				Process pianus = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + archivo3);
			}
	    	 */
         } catch (IOException e1) {
 			// TODO Auto-generated catch block
 			e1.printStackTrace();
 		}
     }
    
     public void redimensionar(Dimension dim, Font fon, String ventana){
    	 
     	 
    	 if (ventana.contains("Mini")){
    		 
             InicioIanus.jButtonTeclas.setMinimumSize(dim);
             InicioIanus.jButtonTeclas.setMaximumSize(dim);
             InicioIanus.jButtonTeclas.setPreferredSize(dim);
             
             jButtonAzules.setMinimumSize(dim);
             jButtonAzules.setMaximumSize(dim);
             jButtonAzules.setPreferredSize(dim);
             
      		 jButton1.setVisible(true);
             jButton9.setVisible(true);
             jButton10.setVisible(true);
             jButton12.setVisible(true);
             InicioIanus.jBultimoNombreSubido.setVisible(true);
             jButton13.setVisible(true);
             
             setSize(new java.awt.Dimension(610, 92));
             setPreferredSize(new java.awt.Dimension(610, 92));
             pack();
    	 }
    	 else if(ventana.contains("Normal")){
    		// jPanel2.setBackground(new Color(255,228,225)); 
    		// jRBmini.setBackground(new Color(255,228,225));
    		 
       		 jButton1.setVisible(true);
             jButton9.setVisible(true);
             jButton10.setVisible(true);
             jButton12.setVisible(true);
             InicioIanus.jBultimoNombreSubido.setVisible(true);
             jButton13.setVisible(true);

             setSize(new java.awt.Dimension(770, 147));
             setPreferredSize(new java.awt.Dimension(770, 147));
             pack();
    	 }
    	 else if(ventana.contains("Micro1")){
    		 
    		 jButton1.setVisible(false);
             jButton9.setVisible(false);
             jButton10.setVisible(false);
             jButton12.setVisible(false);
             InicioIanus.jBultimoNombreSubido.setVisible(false);
             jButton13.setVisible(false);

             setSize(new java.awt.Dimension(410, 110));
             setPreferredSize(new java.awt.Dimension(410, 110));
             pack();

    	 }
    	 else if(ventana.contains("Micro2")){
    		 
    		 jButton1.setVisible(false);
             jButton9.setVisible(false);
             jButton10.setVisible(false);
             jButton12.setVisible(false);
             InicioIanus.jBultimoNombreSubido.setVisible(true);
             jButton13.setVisible(false);

             setSize(new java.awt.Dimension(410, 75));
             setPreferredSize(new java.awt.Dimension(470, 75));
             pack();

    	 }
    	 else if(ventana.contains("Micro3")){
       		 jButton1.setVisible(false);
             jButton9.setVisible(false);
             jButton10.setVisible(false);
             jButton12.setVisible(false);
             InicioIanus.jBultimoNombreSubido.setVisible(true);
             jButton13.setVisible(false);

             jPanel2.setVisible(false);
             
             setSize(new java.awt.Dimension(850, 52));
             setPreferredSize(new java.awt.Dimension(850, 52));
             
                        
             pack();
    		 
    	 }
  	 
    	 
    	 
         jButton1.setMaximumSize(dim);
         jButton1.setMinimumSize(dim);
         jButton1.setPreferredSize(dim);
         jButton1.setFont(fon);
         
         jButton9.setMaximumSize(dim);
         jButton9.setMinimumSize(dim);
         jButton9.setPreferredSize(dim);
         jButton9.setFont(fon);
         
         jButton10.setMaximumSize(dim);
         jButton10.setMinimumSize(dim);
         jButton10.setPreferredSize(dim);
         jButton10.setFont(fon);
         
         jButton12.setMaximumSize(dim);
         jButton12.setMinimumSize(dim);
         jButton12.setPreferredSize(dim);
         jButton12.setFont(fon);
         
         InicioIanus.jBultimoNombreSubido .setMaximumSize(dim);
         InicioIanus.jBultimoNombreSubido .setMinimumSize(dim);
         InicioIanus.jBultimoNombreSubido .setPreferredSize(dim);
         InicioIanus.jBultimoNombreSubido .setFont(fon);
         
         jButton13.setMaximumSize(dim);
         jButton13.setMinimumSize(dim);
         jButton13.setPreferredSize(dim);
         jButton13.setFont(fon);
         
         InicioIanus.teclaAzul1.setMaximumSize(dim);
         InicioIanus.teclaAzul1.setMinimumSize(dim);
         InicioIanus.teclaAzul1.setPreferredSize(dim);
         InicioIanus.teclaAzul1.setFont(fon);
         
         InicioIanus.teclaAzul2.setMaximumSize(dim);
         InicioIanus.teclaAzul2.setMinimumSize(dim);
         InicioIanus.teclaAzul2.setPreferredSize(dim);
         InicioIanus.teclaAzul2.setFont(fon);
         
         pack();
         
     }
     
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel;    

    private javax.swing.JButton jButtonAzules;
    // End of variables declaration
}
