import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Robot;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;

import javax.swing.JButton;
import javax.swing.JPanel;


	public class VentanaAuxiliarBotones extends javax.swing.JFrame {

	    /**
	     * Creates new form VentanaUrgencias
	     */
		int pantallas;
		String[] nomUsualSer = new String[5];
		
	    public VentanaAuxiliarBotones(String[] nombresUsualesServicio) {
			//	Determinar número de pantallas
	    	
	    	for(int i= 0;i<5;i++){
	    		nomUsualSer[i] = nombresUsualesServicio[i];
	    	}
	    	pantallas = InicioIanus.numeroPantallas;
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    private void initComponents() {

	    	setTitle("Habituales");
	    	setSize(650,120);
	    	setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
	    	
	    	
	    	panelN = new JPanel();
	    	panel = new JPanel();
	    	
	    	
	        jButton1 = new JButton(nomUsualSer[0]);
	        jButton2 = new JButton(nomUsualSer[1]);
	        jButton3 = new JButton(nomUsualSer[2]);
	        jButton4 = new JButton(nomUsualSer[3]);
	        jButton5 = new JButton(nomUsualSer[4]);


	        jButton1.setBackground(new java.awt.Color(255, 246, 143));
	        jButton1.setFont(new java.awt.Font("Times", Font.BOLD, 22)); // NOI18N
	        jButton1.setToolTipText("Pega en el Ianus la palabra " + nomUsualSer[0]);
	        
	        jButton2.setBackground(new java.awt.Color(255, 218, 185));
	        jButton2.setFont(new java.awt.Font("Times", 1, 22)); // NOI18N
	        jButton2.setToolTipText("Pega en el Ianus la palabra " + nomUsualSer[1]);
	        
	        jButton3.setBackground(new java.awt.Color(255, 250, 205));
	        jButton3.setFont(new java.awt.Font("Times", 1, 22)); // NOI18N
	        jButton3.setToolTipText("Pega en el Ianus la palabra " + nomUsualSer[2]);
	        
	        jButton4.setBackground(new java.awt.Color(240, 255, 240));
	        jButton4.setFont(new java.awt.Font("Times", 1, 22)); // NOI18N
	        jButton4.setToolTipText("Pega en el Ianus la palabra " + nomUsualSer[3]);
	        
	        jButton5.setBackground(new java.awt.Color(193, 255, 193));
	        jButton5.setFont(new java.awt.Font("Times", 1, 22)); // NOI18N
	        jButton5.setToolTipText("Pega en el Ianus la palabra " + nomUsualSer[4]);
	        
	        
	        
	      //  panelN.setLayout(new BorderLayout());
	        panelN.add(jButton2);
	        panelN.add(jButton3);
	        panelN.add(jButton4);
	        panelN.add(jButton5);        
	        
	        panel.setLayout(new BorderLayout());
	        panel.add(panelN,BorderLayout.SOUTH);
	        panel.add(jButton1,BorderLayout.CENTER);
	        
	        this.setContentPane(panel);
	        
	        //	Clase anónima
	        jButton1.addActionListener (new ActionListener()
	        {
	          public void actionPerformed (ActionEvent e)
	          {
	        	  imprime(nomUsualSer[0]);
	          }
	        });
	        
	        jButton2.addActionListener (new ActionListener()
	        {
	          public void actionPerformed (ActionEvent e)
	          {
	        	  imprime(nomUsualSer[1]);
	          }
	        });
	        
	        jButton3.addActionListener (new ActionListener()
	        {
	          public void actionPerformed (ActionEvent e)
	          {
	        	  imprime(nomUsualSer[2]);
	          }
	        });
	        
	        jButton4.addActionListener (new ActionListener()
	        {
	          public void actionPerformed (ActionEvent e)
	          {
	        	  imprime(nomUsualSer[3]);
	          }
	        });
	        
	        jButton5.addActionListener (new ActionListener()
	        {
	          public void actionPerformed (ActionEvent e)
	          {
	        	  imprime(nomUsualSer[4]);
	          }
	        });
	        pack();
	        this.setVisible(true);
	    }
	    
	        public void imprime(String cadena){
	             RobotIanus robotI = new RobotIanus();
	             InicioIanus.nombreDocumento = cadena;
	             
	             if(InicioIanus.servicioCombo.contains("DIG") && 
	        				(cadena.contains("Enfermería") ||
	        				 cadena.contains("Endoscopia") ||
	        				 cadena.contains("Manometría"))){
	            	 
	/********************************            						InicioIanus.tipoDocAsubir = 1; //	Subir enfermería de dig como ingreso      **************************/
	             
	             }

	             if(pantallas != 1){ pantallas = 4;}
	             
	             
	 //-----------------------------
	           robotI.robotIanus(cadena, 1000, pantallas, InicioIanus.tipoDocAsubir, "", false,false);
	             
	             
	             InicioIanus.estadistica.añadirDato(InicioIanus.servicioCombo, InicioIanus.nombreDocumento);

	             
	       //      InicioIanus.estadistica.
	             
		            if(InicioIanus.numeroIanus==1 || !InicioIanus.par){
			            VentanaExplorador.numArchivo++;
			            int tamañoLista = VentanaExplorador.listaPdfs.getModel().getSize();
			            if(VentanaExplorador.numArchivo<tamañoLista){
			            	VentanaExplorador.listaPdfs.setSelectedIndex(VentanaExplorador.numArchivo);
			            	
			        		int pdfNumero = VentanaExplorador.listaPdfs.getSelectedIndex();
			 
			        		File archivo = new File(InicioIanus.rutaCompletaPdfs[VentanaExplorador.numArchivo]);
			        		try{
//			        			Desktop.getDesktop().open(archivo);
			        			Robot robot = new Robot();
			        			robot.delay(400);
			       			    Process p = Runtime.getRuntime()
		    					        .exec("rundll32 url.dll,FileProtocolHandler " + archivo);		        			
			       			    // Coloca cursor sobre aceptar
			        			robot.mouseMove(1504, 706);
			        		}catch (Exception ev) {
			        			System.out.println(ev);
			        		}
			            }
			            if(InicioIanus.numeroIanus == 2){
			            	VentanaExplorador.numArchivo++;
				            if(VentanaExplorador.numArchivo<tamañoLista){
				            	VentanaExplorador.listaPdfs.setSelectedIndex(VentanaExplorador.numArchivo);
				            	
				        		int pdfNumero = VentanaExplorador.listaPdfs.getSelectedIndex();
				 
				        		File archivo = new File(InicioIanus.rutaCompletaPdfs[VentanaExplorador.numArchivo]);
				        		try{
//				        			Desktop.getDesktop().open(archivo);
			            			Robot robot = new Robot();
			            			robot.delay(400);
				        			Process p = Runtime.getRuntime()
			    					        .exec("rundll32 url.dll,FileProtocolHandler " + archivo);			        			
			

			            			robot.delay(400);
			            			//	Ajusta los documentos horizontalmente

			        				robot.keyPress(KeyEvent.VK_CONTROL);
			        				robot.keyPress(KeyEvent.VK_SHIFT);
			        				robot.keyPress(KeyEvent.VK_K);
			        				robot.keyRelease(KeyEvent.VK_K);
			        				robot.keyRelease(KeyEvent.VK_SHIFT);
			        				robot.keyRelease(KeyEvent.VK_CONTROL);
					         			
				        		}catch (Exception ev) {
				        			System.out.println(ev);
				        		}		            	
				            }
			            }
	        			
		            }
	             
	             
	             
	             
	        }


	    /**
	     * @param args the command line arguments
	     */

	    // Variables declaration - do not modify
	    private JButton jButton1;
	    private JButton jButton2;
	    private JButton jButton3;
	    private JButton jButton4;
	    private JButton jButton5;	    
	    private JPanel panel;
	    private JPanel panelN;
	    // End of variables declaration
	}
	
	
	

